#     APENAS para desenvolvimento local
#    para produção não é recomendável usar assim
version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"
    volumes:
    #   Será armazenado nesse diretório o conteúdo da imagem
    - devdojo_data:/var/lib/mysql

volumes:
  #   Referencia do volume usado
  devdojo_data:
